name: l2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  scratcher: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/items/
    - images/items/sprites/

    - images/pokedex/
    - images/pokedex/hires/
    - images/pokedex/sprites/
    - images/pokedex/thumbnails/

    - images/icons/
